### ISSUE TITLE
Research issue tracking options for AAACT team

### ISSUE THREAD

**Issue by patheard** [dto-btn/todo#7]
This would serve as a potential solution for FORK.

Related #3

**Comment by patheard** [comment]
SYNERGi may be a good fit for a lightweight issue tracker.  Sean is setting up a meeting with the project lead.

**Comment by patheard** [comment]
* GCcase could be another option.
* Need to research open source issue trackers next.

**Comment by patheard** [comment]
Met with SYNERGi team this morning - here are notes from the meeting:

# Process for requesting site
1. Request site on SYNERGi.
1. Identify administrators (recommended two) and send on mandatory training.
1. Meet with SYNERGi team BAs to determine site requirements.
1. Develop site with SYNERGi  team or on your own.
1. Development and maintenance cost is free.

# Data
* If data can be exported to an Excel spreadsheet, it can be imported.
* SYNERGi team will assist with import.
* Data changes can be version controlled (view history of changes).

# Roles
* Site admin: full access.
* Contributor: create, edit and delete content.
* Visitor: read-only view of data.

# Considerations
* Mobile experience is not good.
* There may be work required to meet WCAG 2.1 AA.
* Client can introduce custom CSS/JS (e.g. high contrast mode), but this can cause support issues since SYNERGi does not support custom code.
* Sometimes issues with copying/pasting data.
* No support for external API (e.g. validation of user data from GEDS).

**Comment by britthurley** [comment]
Contacted accessibility lead @ CDS Julianna for additional recommendations.

**Comment by patheard** [comment]
CCM is being investigated to see if it meets the accessibility requirements.

**Comment by patheard** [comment]
Closing.  Can be reopened if further activity from our team is needed.
